Practice

In [2]:
import pandas as pd

In [15]:
data={
    'name': ['shiva', 'sai', 'ram', 'krishna'],
    'age': [25, 30, 35, 40],
    'city': ['Rajahmundry', 'Hyderabad', 'Vijayawada', 'Guntur'],
    'salary': [40000, 60000, 70000, 80000],
    'Department': ['HR', 'IT', 'Finance', 'Marketing'],
}
df=pd.DataFrame(data)
df

      name  age         city  salary Department
0    shiva   25  Rajahmundry   40000         HR
1      sai   30    Hyderabad   60000         IT
2      ram   35   Vijayawada   70000    Finance
3  krishna   40       Guntur   80000  Marketing

In [18]:
df[df['salary'] > 50000]

      name  age        city  salary Department
1      sai   30   Hyderabad   60000         IT
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [19]:
result=df[(df['salary'] > 50000) & (df['age'] > 30)]
result

      name  age        city  salary Department
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [20]:
df[(df['salary']>60000) | (df['age']>30)]

      name  age        city  salary Department
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [21]:
df[df['city'].isin(['Hyderabad', 'Vijayawada'])]

  name  age        city  salary Department
1  sai   30   Hyderabad   60000         IT
2  ram   35  Vijayawada   70000    Finance

In [22]:
df.sort_values('salary', ascending=False)

      name  age         city  salary Department
3  krishna   40       Guntur   80000  Marketing
2      ram   35   Vijayawada   70000    Finance
1      sai   30    Hyderabad   60000         IT
0    shiva   25  Rajahmundry   40000         HR

In [23]:
df.sort_values('salary')

      name  age         city  salary Department
0    shiva   25  Rajahmundry   40000         HR
1      sai   30    Hyderabad   60000         IT
2      ram   35   Vijayawada   70000    Finance
3  krishna   40       Guntur   80000  Marketing

In [24]:
df.sort_values(['salary', 'age'], ascending=[False, True])

      name  age         city  salary Department
3  krishna   40       Guntur   80000  Marketing
2      ram   35   Vijayawada   70000    Finance
1      sai   30    Hyderabad   60000         IT
0    shiva   25  Rajahmundry   40000         HR

In [25]:
df['Scholar']=df['age']>=35

In [26]:
df

      name  age         city  salary Department  Scholar
0    shiva   25  Rajahmundry   40000         HR    False
1      sai   30    Hyderabad   60000         IT    False
2      ram   35   Vijayawada   70000    Finance     True
3  krishna   40       Guntur   80000  Marketing     True

In [29]:
df['total']=df['salary']+df['Scholar']
df

      name  age         city  salary Department  Scholar  total
0    shiva   25  Rajahmundry   40000         HR    False  40000
1      sai   30    Hyderabad   60000         IT    False  60000
2      ram   35   Vijayawada   70000    Finance     True  70001
3  krishna   40       Guntur   80000  Marketing     True  80001

In [30]:
import numpy as np

In [31]:
df['level']=np.where(df['age']>30, 'Senior', 'Junior')

In [32]:
df

      name  age         city  salary Department  Scholar  total   level
0    shiva   25  Rajahmundry   40000         HR    False  40000  Junior
1      sai   30    Hyderabad   60000         IT    False  60000  Junior
2      ram   35   Vijayawada   70000    Finance     True  70001  Senior
3  krishna   40       Guntur   80000  Marketing     True  80001  Senior

In [34]:
r=df.groupby('Department')['salary'].mean()
r

Department
Finance      70000.0
HR           40000.0
IT           60000.0
Marketing    80000.0
Name: salary, dtype: float64

In [37]:
r=df.groupby(['Department', 'Scholar'])['salary'].agg(['mean', 'sum', 'max', 'min','count'])
r

                       mean    sum    max    min  count
Department Scholar
Finance    True     70000.0  70000  70000  70000      1
HR         False    40000.0  40000  40000  40000      1
IT         False    60000.0  60000  60000  60000      1
Marketing  True     80000.0  80000  80000  80000      1

In [39]:
r=df.groupby('city')['salary'].mean()
r

city
Guntur         80000.0
Hyderabad      60000.0
Rajahmundry    40000.0
Vijayawada     70000.0
Name: salary, dtype: float64

In [40]:
df['name'].value_counts()

name
shiva      1
sai        1
ram        1
krishna    1
Name: count, dtype: int64

In [47]:
r=df.groupby(['city','Department'])['salary'].max()
r

city         Department
Guntur       Marketing     80000
Hyderabad    IT            60000
Rajahmundry  HR            40000
Vijayawada   Finance       70000
Name: salary, dtype: int64

In [48]:
df.isnull().sum()

name          0
age           0
city          0
salary        0
Department    0
Scholar       0
total         0
level         0
dtype: int64

In [49]:
df["Department"].value_counts()

Department
HR           1
IT           1
Finance      1
Marketing    1
Name: count, dtype: int64

In [50]:
df.drop_duplicates()

      name  age         city  salary Department  Scholar  total   level
0    shiva   25  Rajahmundry   40000         HR    False  40000  Junior
1      sai   30    Hyderabad   60000         IT    False  60000  Junior
2      ram   35   Vijayawada   70000    Finance     True  70001  Senior
3  krishna   40       Guntur   80000  Marketing     True  80001  Senior

In [4]:
df.rename=[columns={'scholar':'=Bonus'} ]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2344562990.py, line 1)