Practice

In [8]:
import pandas as pd

In [9]:
data={
    'name': ['shiva', 'sai', 'ram', 'krishna'],
    'age': [25, 30, 35, 40],
    'city': ['Rajahmundry', 'Hyderabad', 'Vijayawada', 'Guntur'],
    'salary': [40000, 60000, 70000, 80000],
    'Department': ['HR', 'IT', 'Finance', 'Marketing'],
}
df=pd.DataFrame(data)
df

      name  age         city  salary Department
0    shiva   25  Rajahmundry   40000         HR
1      sai   30    Hyderabad   60000         IT
2      ram   35   Vijayawada   70000    Finance
3  krishna   40       Guntur   80000  Marketing

In [10]:
df[df['salary'] > 50000]

      name  age        city  salary Department
1      sai   30   Hyderabad   60000         IT
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [11]:
result=df[(df['salary'] > 50000) & (df['age'] > 30)]
result

      name  age        city  salary Department
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [12]:
df[(df['salary']>60000) | (df['age']>30)]

      name  age        city  salary Department
2      ram   35  Vijayawada   70000    Finance
3  krishna   40      Guntur   80000  Marketing

In [13]:
df[df['city'].isin(['Hyderabad', 'Vijayawada'])]

  name  age        city  salary Department
1  sai   30   Hyderabad   60000         IT
2  ram   35  Vijayawada   70000    Finance

In [14]:
df.sort_values('salary', ascending=False)

      name  age         city  salary Department
3  krishna   40       Guntur   80000  Marketing
2      ram   35   Vijayawada   70000    Finance
1      sai   30    Hyderabad   60000         IT
0    shiva   25  Rajahmundry   40000         HR

In [15]:
df.sort_values('salary')

      name  age         city  salary Department
0    shiva   25  Rajahmundry   40000         HR
1      sai   30    Hyderabad   60000         IT
2      ram   35   Vijayawada   70000    Finance
3  krishna   40       Guntur   80000  Marketing

In [16]:
df.sort_values(['salary', 'age'], ascending=[False, True])

      name  age         city  salary Department
3  krishna   40       Guntur   80000  Marketing
2      ram   35   Vijayawada   70000    Finance
1      sai   30    Hyderabad   60000         IT
0    shiva   25  Rajahmundry   40000         HR

In [17]:
df['Scholar']=df['age']>=35

In [18]:
df

      name  age         city  salary Department  Scholar
0    shiva   25  Rajahmundry   40000         HR    False
1      sai   30    Hyderabad   60000         IT    False
2      ram   35   Vijayawada   70000    Finance     True
3  krishna   40       Guntur   80000  Marketing     True

In [19]:
df['total']=df['salary']+df['Scholar']
df

      name  age         city  salary Department  Scholar  total
0    shiva   25  Rajahmundry   40000         HR    False  40000
1      sai   30    Hyderabad   60000         IT    False  60000
2      ram   35   Vijayawada   70000    Finance     True  70001
3  krishna   40       Guntur   80000  Marketing     True  80001

In [20]:
import numpy as np

In [21]:
df['level']=np.where(df['age']>30, 'Senior', 'Junior')

In [22]:
df

      name  age         city  salary Department  Scholar  total   level
0    shiva   25  Rajahmundry   40000         HR    False  40000  Junior
1      sai   30    Hyderabad   60000         IT    False  60000  Junior
2      ram   35   Vijayawada   70000    Finance     True  70001  Senior
3  krishna   40       Guntur   80000  Marketing     True  80001  Senior

In [23]:
r=df.groupby('Department')['salary'].mean()
r

Department
Finance      70000.0
HR           40000.0
IT           60000.0
Marketing    80000.0
Name: salary, dtype: float64

In [24]:
r=df.groupby(['Department', 'Scholar'])['salary'].agg(['mean', 'sum', 'max', 'min','count'])
r

                       mean    sum    max    min  count
Department Scholar
Finance    True     70000.0  70000  70000  70000      1
HR         False    40000.0  40000  40000  40000      1
IT         False    60000.0  60000  60000  60000      1
Marketing  True     80000.0  80000  80000  80000      1

In [25]:
r=df.groupby('city')['salary'].mean()
r

city
Guntur         80000.0
Hyderabad      60000.0
Rajahmundry    40000.0
Vijayawada     70000.0
Name: salary, dtype: float64

In [26]:
df['name'].value_counts()

name
shiva      1
sai        1
ram        1
krishna    1
Name: count, dtype: int64

In [27]:
r=df.groupby(['city','Department'])['salary'].max()
r

city         Department
Guntur       Marketing     80000
Hyderabad    IT            60000
Rajahmundry  HR            40000
Vijayawada   Finance       70000
Name: salary, dtype: int64

In [28]:
df.isnull().sum()

name          0
age           0
city          0
salary        0
Department    0
Scholar       0
total         0
level         0
dtype: int64

In [29]:
df["Department"].value_counts()

Department
HR           1
IT           1
Finance      1
Marketing    1
Name: count, dtype: int64

In [30]:
df.drop_duplicates()

      name  age         city  salary Department  Scholar  total   level
0    shiva   25  Rajahmundry   40000         HR    False  40000  Junior
1      sai   30    Hyderabad   60000         IT    False  60000  Junior
2      ram   35   Vijayawada   70000    Finance     True  70001  Senior
3  krishna   40       Guntur   80000  Marketing     True  80001  Senior

In [31]:
df.columns

Index(['name', 'age', 'city', 'salary', 'Department', 'Scholar', 'total',
       'level'],
      dtype='str')

In [32]:
df.rename(columns={'scholar': 'Bonus'}, inplace=True)

In [33]:
df

      name  age         city  salary Department  Scholar  total   level
0    shiva   25  Rajahmundry   40000         HR    False  40000  Junior
1      sai   30    Hyderabad   60000         IT    False  60000  Junior
2      ram   35   Vijayawada   70000    Finance     True  70001  Senior
3  krishna   40       Guntur   80000  Marketing     True  80001  Senior

In [34]:
df.rename(columns={'Scholar': 'Bonus'}, inplace=True)
df

      name  age         city  salary Department  Bonus  total   level
0    shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1      sai   30    Hyderabad   60000         IT  False  60000  Junior
2      ram   35   Vijayawada   70000    Finance   True  70001  Senior
3  krishna   40       Guntur   80000  Marketing   True  80001  Senior

In [35]:
df.columns

Index(['name', 'age', 'city', 'salary', 'Department', 'Bonus', 'total',
       'level'],
      dtype='str')

In [36]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [37]:
df.max()

name               shiva
age                   40
city          Vijayawada
salary             80000
Department     Marketing
Bonus               True
total              80001
level             Senior
dtype: object

In [38]:
df.iloc[0]
df

      name  age         city  salary Department  Bonus  total   level
0    shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1      sai   30    Hyderabad   60000         IT  False  60000  Junior
2      ram   35   Vijayawada   70000    Finance   True  70001  Senior
3  krishna   40       Guntur   80000  Marketing   True  80001  Senior

In [39]:
df.loc[0]
df

      name  age         city  salary Department  Bonus  total   level
0    shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1      sai   30    Hyderabad   60000         IT  False  60000  Junior
2      ram   35   Vijayawada   70000    Finance   True  70001  Senior
3  krishna   40       Guntur   80000  Marketing   True  80001  Senior

In [40]:
df.iloc[df['salary'] > 30000]
df

      name  age         city  salary Department  Bonus  total   level
0    shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1      sai   30    Hyderabad   60000         IT  False  60000  Junior
2      ram   35   Vijayawada   70000    Finance   True  70001  Senior
3  krishna   40       Guntur   80000  Marketing   True  80001  Senior

In [41]:
df.iloc[df['salary'] > 50000]
df

      name  age         city  salary Department  Bonus  total   level
0    shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1      sai   30    Hyderabad   60000         IT  False  60000  Junior
2      ram   35   Vijayawada   70000    Finance   True  70001  Senior
3  krishna   40       Guntur   80000  Marketing   True  80001  Senior

In [42]:
df.iloc[0:2]

    name  age         city  salary Department  Bonus  total   level
0  shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1    sai   30    Hyderabad   60000         IT  False  60000  Junior

In [43]:
df.loc[0:2]

    name  age         city  salary Department  Bonus  total   level
0  shiva   25  Rajahmundry   40000         HR  False  40000  Junior
1    sai   30    Hyderabad   60000         IT  False  60000  Junior
2    ram   35   Vijayawada   70000    Finance   True  70001  Senior